services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data


  web-app:
    build:
      context: .
    image: service
    container_name: service
    restart: always
    command: 'python manage.py runserver 0.0.0.0:8000'
    env_file:
      - .env
    links:
      - "postgres:dbps"
    volumes:
      - ./service:/service
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  telegram-bot:
    build: .
    container_name: telegram-bot
    command: 'python -c "from telegram_bot import run_bot; run_bot()"'
    env_file: .env
    volumes:
      - ./service:/service
    links:
      - "postgres:dbps"
    depends_on:
      - postgres
      - web-app


volumes:
  postgres-data: